/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ItineraryBuilderRouteImport } from './routes/itinerary-builder'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateTripRouteImport } from './routes/create-trip'
import { Route as IndexRouteImport } from './routes/index'

const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryBuilderRoute = ItineraryBuilderRouteImport.update({
  id: '/itinerary-builder',
  path: '/itinerary-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTripRoute = CreateTripRouteImport.update({
  id: '/create-trip',
  path: '/create-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-trip': typeof CreateTripRoute
  '/dashboard': typeof DashboardRoute
  '/itinerary-builder': typeof ItineraryBuilderRoute
  '/login': typeof LoginRoute
  '/my-trips': typeof MyTripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-trip': typeof CreateTripRoute
  '/dashboard': typeof DashboardRoute
  '/itinerary-builder': typeof ItineraryBuilderRoute
  '/login': typeof LoginRoute
  '/my-trips': typeof MyTripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-trip': typeof CreateTripRoute
  '/dashboard': typeof DashboardRoute
  '/itinerary-builder': typeof ItineraryBuilderRoute
  '/login': typeof LoginRoute
  '/my-trips': typeof MyTripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-trip'
    | '/dashboard'
    | '/itinerary-builder'
    | '/login'
    | '/my-trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-trip'
    | '/dashboard'
    | '/itinerary-builder'
    | '/login'
    | '/my-trips'
  id:
    | '__root__'
    | '/'
    | '/create-trip'
    | '/dashboard'
    | '/itinerary-builder'
    | '/login'
    | '/my-trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateTripRoute: typeof CreateTripRoute
  DashboardRoute: typeof DashboardRoute
  ItineraryBuilderRoute: typeof ItineraryBuilderRoute
  LoginRoute: typeof LoginRoute
  MyTripsRoute: typeof MyTripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary-builder': {
      id: '/itinerary-builder'
      path: '/itinerary-builder'
      fullPath: '/itinerary-builder'
      preLoaderRoute: typeof ItineraryBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-trip': {
      id: '/create-trip'
      path: '/create-trip'
      fullPath: '/create-trip'
      preLoaderRoute: typeof CreateTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateTripRoute: CreateTripRoute,
  DashboardRoute: DashboardRoute,
  ItineraryBuilderRoute: ItineraryBuilderRoute,
  LoginRoute: LoginRoute,
  MyTripsRoute: MyTripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
